spring.datasource.url=jdbc:postgresql://trolley.proxy.rlwy.net:28429/railway
spring.datasource.username=postgres
spring.datasource.password=NgWQDpxAXqkuJTxtvZkUAgOyKNquQXOf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=72c98996f94a0c0bad76498d12eeb0f43771ad54eaffdaf72cff8e272573931c